[package]
name = "pwintln"
version = "0.1.0"
authors = ["lf- <lf-@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.80"
xmas-elf = "0.7.0"
zero = "0.1"
goblin = "0.2.3"
plain = "0.2.3"
